[package]
name = "slang"
version = "0.1.0"
authors = ["Brandon Davis <dbrandon.91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
